Merging current prod to test
CityOfLosAngeles/open-sdg-data-starter pull request #4
Opened 2020-12-22 00:57 UTC by Paz-X

2021-01-14 01:39 UTC, jaylenw requested changes
@Paz-X please fill in the PR description with the appropriate details and make the requested changes. Thanks!

Tested this locally by running `pip3 install -r scripts/requirements.txt && python3 scripts/build_data.pyon3 scripts/build_data.py` with no issue.

2021-01-14 01:39 UTC, jaylenw commented on README.md
> -# Open SDG - Data starter ![Build and Deploy Development Data](https://github.com/CityOfLosAngeles/open-sdg-data-starter/workflows/Build%20and%20Deploy%20Development%20Data/badge.svg) ![Build and Dep
Keep the markdown image links so that we can see the workflow status in the default branch.

2021-01-22 00:23 UTC, jaylenw approved these changes

2021-02-04 17:05 UTC, RV-LACity approved these changes

2021-02-04 17:43 UTC, merged